apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: jira-get-issues
description: "Get Jira issues using JQL query"
inputs:
  jira-url:
    description: "Jira instance URL (e.g., https://your-domain.atlassian.net)"
    required: true
  jira-username:
    description: "Jira username or email address"
    required: true
  jira-token:
    description: "Jira API token"
    required: true
  jql:
    description: "JQL query to find issues"
    required: true
  fields:
    description: "Comma-separated list of fields to return (e.g. 'summary,status,assignee')"
    required: false
  max-results:
    description: "Maximum number of issues to return"
    default: "50"
    required: false

outputs:
  total:
    value: ${{ steps.get-issues.outputs.total }}
    description: "Total number of issues found"
  issues:
    value: ${{ steps.get-issues.outputs.issues }}
    description: "JSON array of issues found"

runs:
  using: composite
  steps:
    - id: get-issues
      name: Get Jira Issues
      uses: docker://ldonleycb/jira-actions:latest
      shell: sh
      run: |
        /app/jira-actions get-issues \
          --url "${{ inputs.jira-url }}" \
          --username "${{ inputs.jira-username }}" \
          --token "${{ inputs.jira-token }}" \
          --jql '${{ inputs.jql }}' \
          ${{ inputs.fields && format('--fields "{0}"', inputs.fields) || '' }} \
          --max-results "${{ inputs.max-results }}" \
          --verbose
